name: Vercel Deployment Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Vercel
        uses: vercel/repository-dispatch@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          name: 'Vercel - afton-industries-official-website: lint'
